name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install godoc
        run: go install golang.org/x/tools/cmd/godoc@latest

      - name: Generate GoDoc
        run: |
          mkdir -p docs
          godoc -http=:6060 &
          sleep 10
          wget -r -np -P docs -nH --cut-dirs=5 -E -k -K -p --reject "robots.txt" --no-parent http://localhost:6060/pkg/github.com/pzentenoe/gorm-connection/sql/ || true
      - name: Create .nojekyll
        run: echo "" > docs/.nojekyll
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
